### PR TITLE
Add pretty formatting and style for trees (such as merged threads stacks)

### PR DESCRIPTION
**Pull request by ogxd**

### CODE REVIEW

**Comment by ogxd** [comment]
There's some repetitions in CSS but unfortunately grouping is a SASS features and need a specific compiler plugin that I think we shouldn't force people to install

**Comment by ogxd** [comment]
This package includes a SASS compiler but this is all relying on some native libs I am not a fan https://www.nuget.org/packages/LibSassBuilder/

**Comment by Bluezen** [comment]
IMHO the css is ok as it is, I think we can do without sass.
I have made the minimal changes required for the mergedCallstacks profiler to output HTML. The whole profiler could benefit from some refactoring but for now it allows us to compare the markdown to the HTML …

**Review by Bluezen — APPROVED** [review]
Nice 😎

**Pull request merged**
